# This workflow will build and publish a new Docker image to JFrog Container Registry

name: Build and publish to JFrog

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  JF_URL: dadjokes.jfrog.io
  JF_ACCESS_TOKEN: ${{ secrets.JFROG_TOKEN }}
  IMAGE_NAME: dadjokes.jfrog.io/docker/petclinic-image:latest

jobs:
  build_and_publish_container:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
       
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3

      - name: Build tag and Push Docker Image
        run: |
          jf docker build -t $IMAGE_NAME .
          jf docker push $IMAGE_NAME

      - name: Scan local Docker image with XRay
        run: |
          jf docker scan --format=json $IMAGE_NAME >> ${{ github.workspace }}/scan_results.json

      - name: Upload JSON scan results as workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: scan_results
          path: ${{ github.workspace }}/scan_results.json
          
      - name: Publish Build info With JFrog CLI
        env:
          JFROG_CLI_BUILD_NAME: jfrog-docker-petclinic
          JFROG_CLI_BUILD_NUMBER : ${{ github.sha }}
        run: |
          # Export the build name and build nuber
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish
